// SupportingApplications/BO_React/src/components/StatusBar.tsx
import React from 'react';

interface StatusBarProps {
  status: string;
  type?: 'info' | 'success' | 'warning' | 'error' | 'loading';
  loading?: boolean;
}

const getStatusIcon = (type: StatusBarProps['type']) => {
  const icons = {
    info: 'bi-info-circle',
    success: 'bi-check-circle',
    warning: 'bi-exclamation-triangle',
    error: 'bi-exclamation-circle',
    loading: 'bi-arrow-repeat'
  };
  return `bi ${icons[type || 'info']}`;
};

const getStatusClass = (type: StatusBarProps['type']) => {
  const classes = {
    info: 'text-info',
    success: 'text-success',
    warning: 'text-warning',
    error: 'text-danger',
    loading: 'text-primary'
  };
  return classes[type || 'info'];
};

export const StatusBar: React.FC<StatusBarProps> = ({ 
  status, 
  type = 'info', 
  loading = false 
}) => {
  return (
    <div className="status-bar">
      <div className="d-flex align-items-center justify-content-between">
        <div className="d-flex align-items-center">
          <i className={`${getStatusIcon(type)} ${getStatusClass(type)} me-2`}></i>
          <span className="fw-medium">{status}</span>
        </div>
        {loading && <div className="loading-spinner"></div>}
      </div>
    </div>
  );
};

// SupportingApplications/BO_React/SupportingApplications/BO_Vue3/src/components/StatusBar.vue
<template>
  <div class="status-bar">
    <div class="d-flex align-items-center justify-content-between">
      <div class="d-flex align-items-center">
        <i class="bi bi-info-circle me-2"></i>
        <span class="fw-medium">{{ status }}</span>
      </div>
      <div v-if="loading" class="loading-spinner"></div>
    </div>
  </div>
</template>

<script setup lang="ts">
interface Props {
  status: string
  type?: 'info' | 'success' | 'warning' | 'error' | 'loading'
  loading?: boolean
}

withDefaults(defineProps<Props>(), {
  type: 'info',
  loading: false
})
</script>
